artifact_location: /Users/maukanmir/Documents/Machine-Learning/ML-OPS-Projects/ML-FLOW-Guide/myracks/0
creation_time: 1717616153386
experiment_id: '0'
last_update_time: 1717616153386
lifecycle_stage: active
name: Default
