artifact_uri: /Users/maukanmir/Documents/Machine-Learning/ML-OPS-Projects/ML-FLOW-Guide/myracks/544420180745646108/61a0fc2b206b4cc4ad25bed0c117c15f/artifacts
end_time: 1717616154811
entry_point_name: ''
experiment_id: '544420180745646108'
lifecycle_stage: active
run_id: 61a0fc2b206b4cc4ad25bed0c117c15f
run_name: valuable-kit-964
run_uuid: 61a0fc2b206b4cc4ad25bed0c117c15f
source_name: ''
source_type: 4
source_version: ''
start_time: 1717616153539
status: 3
tags: []
user_id: maukanmir
