artifact_location: /Users/maukanmir/Documents/Machine-Learning/ML-OPS-Projects/ML-FLOW-Guide/myracks/544420180745646108
creation_time: 1717616153390
experiment_id: '544420180745646108'
last_update_time: 1717616153390
lifecycle_stage: active
name: exp_for_ui
