artifact_location: file:///Users/maukanmir/Documents/Machine-Learning/ML-OPS-Projects/ML-FLOW-Guide/test1/0
creation_time: 1717616272941
experiment_id: '0'
last_update_time: 1717616272941
lifecycle_stage: active
name: Default
